config/routes.rb
Rails.application.routes.draw do
  # 会員用
  devise_for :members, skip: [:passwords], controllers: 
  {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:
  {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "members_guest_sign_in"
  end
  
  scope module: :public do
    root to: "homes#top"
    
    get '/canned_foods/search' => 'canned_foods#search'
    get "/canned_foods/search_tag" => "canned_foods#search_tag"
    resources :canned_foods, only: [:index, :show]do
      resources :reviews, only: [:index]
    end
    
    get '/members/my_page' => 'members#index'
    get '/members/information/edit' => 'members#edit'
    patch '/members/information' => 'members#update'
    get '/members/unsubscribe' => 'members#unsubscribe'
    patch '/members/withdraw' => 'members#withdraw'
    resources :members, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    
    resources :reviews, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :index, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
    
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    
    # 新規会員登録失敗時の対処
    get "members" => redirect("/members/sign_up")
  end
  
  namespace :admin do
    resources :canned_foods, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index]
    end
    
    resources :members, only: [:index, :show, :edit, :update] 
    
    get '/members/:member_id/reviews' => 'reviews#show', as: "reviews_member"
    resources :reviews, only: [:destroy] do
      resources :comments, only: [:index, :destroy]
    end
    
    get "search" => "searches#search"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member  # 会員に所属
  belongs_to :review  # レビューに所属

  # コメントの画像用
  has_one_attached :image
  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  validates :content, presence: true, length: { in: 1..100 }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @review = Review.find(params[:review_id])
    @canned_food = @review.canned_food
    @tags = @canned_food.tags

    # 削除されたページ数を計算し、現在のページ番号が削除範囲を超えている場合は修正する
    deleted_page = (@review.comments.count / 5.0).ceil
    if params[:page].to_i > deleted_page
      params[:page] = deleted_page.to_s
    end

    # 削除後にページネーションを更新
    @comments = @review.comments.page(params[:page]).per(5)
  end

  def destroy
    comment = Comment.find(params[:id])

    if comment.destroy
      flash[:notice] = "コメントを削除しました。"
      redirect_to request.referer
    else
      flash[:alert] = "コメントの削除が失敗しました。"
      render :index
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comment_list.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead class="text-center">
    <th>投稿者</th>
    <th>画像</th>
    <th>コメント内容</th>
    <th></th>
  </thead>
  <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td class="col-2 text-center">
          <%= link_to admin_member_path(comment.member) do %>
            <%= image_tag comment.member.get_profile_image(50,50), class: "image" %><br>
            <%= comment.member.nickname %>
          <% end %>
        </td>
        <td class="col-2 text-center">
          <% if comment.image.attached? %>
            <%= image_tag comment.get_image(100,100), class: "image" %>
          <% end %>
        </td>
        <td class="col-6 text-break">
          <%=safe_join(comment.content.split("\n"),tag(:br))%>
        </td>
        <td class="col-2 text-center">
          <%= link_to "削除", admin_review_comment_path(review, comment), method: :delete, class: "btn btn-sm btn-danger float-end px-3" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/comments/_count.html.erb
コメント数： <%= comment.count %>

app/views/admin/comments/index.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">レビュー詳細</h2>
  </div>
  
  <div class="row my-5 justify-content-center">
    <div class="col-lg-4 col-md-12 text-center">
      <%= link_to admin_canned_food_path(@canned_food.id) do %>
        <div>
          <%= image_tag @canned_food.get_image(200,100), class: "image" %>
        </div>
        <div>
          缶詰名： <%= @canned_food.canned_name %>
        </div>
      <% end %>
      <div>
        <% @tags.each do |tag| %>
          タグ： <%= tag.name %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-8 col-md-12 border border-primary text-break overflow-auto description-box">
      <%=safe_join(@canned_food.description.split("\n"),tag(:br))%>
    </div>
  </div>
  
  <div class="row my-5 text-center">
    <div class="col-12">
      <h5 class="row justify-content-center">
        <%= link_to admin_member_path(@review.member) do %>
          <%= @review.member.nickname %>
        <% end %>
        さんの評価
      </h5>
      
      <div class="row mt-3">
        <%= render "admin/reviews/review_read_only", review: @review %>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <h5 class="col-12 text-center">
      コメント一覧（
      <%= render "count", comment: @review.comments %>
      ）
    </h5>
  </div>

  <div class="row my-3 justify-content-center">
    <div class="col-12">
      <%= render "comment_list", comments: @comments, review: @review %>
    </div>
  </div>
  
  <div class="row">
    <div class="mx-auto my-2">
      <%= paginate @comments %>
    </div>
  </div>
</div>