config/routes.rb
Rails.application.routes.draw do
  # 会員用
  devise_for :members, skip: [:passwords], controllers: 
  {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:
  {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "members_guest_sign_in"
  end
  
  scope module: :public do
    root to: "homes#top"
    
    get '/canned_foods/search' => 'canned_foods#search'
    get "/canned_foods/search_tag" => "canned_foods#search_tag"
    resources :canned_foods, only: [:index, :show]do
      resources :reviews, only: [:index]
    end
    
    get '/members/my_page' => 'members#index'
    get '/members/information/edit' => 'members#edit'
    patch '/members/information' => 'members#update'
    get '/members/unsubscribe' => 'members#unsubscribe'
    patch '/members/withdraw' => 'members#withdraw'
    resources :members, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    
    resources :reviews, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :index, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
    
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    
    # 新規会員登録失敗時の対処
    get "members" => redirect("/members/sign_up")
  end
  
  namespace :admin do
    resources :canned_foods, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index]
    end
    
    resources :members, only: [:index, :show, :edit, :update] 
    
    get '/members/:member_id/reviews' => 'reviews#show', as: "reviews_member"
    resources :reviews, only: [:destroy] do
      resources :comments, only: [:index, :destroy]
    end
    
    get "search" => "searches#search"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @canned_food = CannedFood.find(params[:canned_food_id])
    @tags = @canned_food.tags

    # 削除されたページ数を計算し、現在のページ番号が削除範囲を超えている場合は修正する
    deleted_page = (@canned_food.reviews.count / 5.0).ceil
    if params[:page].to_i > deleted_page
      params[:page] = deleted_page.to_s
    end

    # 削除後にページネーションを更新
    @reviews = @canned_food.reviews.page(params[:page]).per(5)
  end

  def show
    @member = Member.find(params[:member_id])
    @reviews = @member.reviews.page(params[:page]).per(5)
  end

  def destroy
    review = Review.find(params[:id])

    if review.destroy
      flash[:notice] = "レビューを削除しました。"
      redirect_to request.referer
    else
      flash[:alert] = "レビューの削除が失敗しました。"
      render :show
    end
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_display.html.erb
<div class="col-lg-3 col-md-12 my-2 text-center">
  賞味期限
  <%= render "admin/reviews/rate_read_only", review: review, type: 'expiry_date_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  おいしさ
  <%= render "admin/reviews/rate_read_only", review: review, type: 'taste_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  おつまみ
  <%= render "admin/reviews/rate_read_only", review: review, type: 'snack_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  アウトドア
  <%= render "admin/reviews/rate_read_only", review: review, type: 'outdoor_rating' %>
</div>

app/views/admin/reviews/_rate_read_only.html.erb
<div class="detail-value", id="<%= type %>-<%= review.id %>"></div> <%# .idでどの評価であるかを取得 %>

<script>
  // Turbolinksで星が増殖する現象を解消
  $('#<%= type %>-<%= review.id %>').empty(); 
  
  raty(document.querySelector('#<%= type %>-<%= review.id %>'),{
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    
    // scoreオプションで最初の評価内容を取得
    <% if type == "expiry_date_rating" %> 
      score   : '<%= review.expiry_date_rating %>',    
    <% end %>
    <% if type == "taste_rating" %> 
      score   : '<%= review.taste_rating %>',
    <% end %>
    <% if type == "snack_rating" %> 
      score   : '<%= review.snack_rating %>',
    <% end %>
    <% if type == "outdoor_rating" %> 
      score   : '<%= review.outdoor_rating %>',
    <% end %>
    
    half      : false,
    readOnly  : true,
  });
</script>

app/views/admin/reviews/_review_read_only.html.erb
<div class="col-lg-3 col-md-12 my-2 text-center">
  賞味期限
  <%= render "admin/reviews/rate_read_only", review: review, type: 'expiry_date_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  おいしさ
  <%= render "admin/reviews/rate_read_only", review: review, type: 'taste_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  おつまみ
  <%= render "admin/reviews/rate_read_only", review: review, type: 'snack_rating' %>
</div>
<div class="col-lg-3 col-md-12 my-2 text-center">
  アウトドア
  <%= render "admin/reviews/rate_read_only", review: review, type: 'outdoor_rating' %>
</div>

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">
      レビュー一覧
    </h2>
    <div class="col-md-auto col-sm-12 justify-content-center d-flex align-items-center">
      (レビュー数：<%= @canned_food.reviews.count %>)
    </div>
  </div>
  
  <div class="row my-5 justify-content-center">
    <div class="col-lg-3 col-md-12 text-center">
      <%= link_to admin_canned_food_path(@canned_food.id) do %>
        <div>
          <%= image_tag @canned_food.get_image(200,100), class: "image" %>
        </div>
        <div>
          缶詰名： <%= @canned_food.canned_name %>
        </div>
      <% end %>
      <div>
        <% @tags.each do |tag| %>
          タグ： <%= tag.name %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6 col-md-12 border border-primary text-break overflow-auto description-box">
      <%=safe_join(@canned_food.description.split("\n"),tag(:br))%>
    </div>
  </div>
  
  <!-- 缶詰へのレビュー一覧 -->
  <% if @reviews.present? %>
    <% @reviews.each do |review| %>
      <div class="row my-3 justify-content-center">
        <div class="col-lg-3 col-md-12 p-3 text-center display-box">
          <%= link_to admin_member_path(review.member) do %>
            <%= image_tag review.member.get_profile_image(100,100), class: "image" %><br>
            <%= review.member.nickname %>
          <% end %>  
        </div>
        <div class="col-lg-9 col-md-12 d-flex align-items-center justify-content-center display-box">
          <div class="row">
            <%= render "display", review: review %>
            <div class="col-12 text-center">
              <%= render "admin/comments/count", comment: review.comments %>
            </div>
            <div class="col-12 my-3 text-center">
              <%= link_to "レビュー詳細", admin_review_comments_path(review.id), class: "btn primary-button" %>
              <%= link_to "レビュー削除", admin_review_path(review.id), method: :delete, class: 'btn danger-button' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col my-5 text-center justify-content-center">
      <h3>この缶詰へのレビューはありません。</h3>
    </div>
  <% end %>
  
  <div class="row">
    <div class="mx-auto my-5">
      <%= paginate @reviews %>
    </div>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="px-3 text-center">
      <%= @member.nickname %>さんのレビュー一覧
    </h2>
    <div class="col-md-auto col-sm-12 justify-content-center d-flex align-items-center">
       (レビュー数： <%= @member.reviews.count %>)
    </div>
  </div>
  
  <div class="row my-4 text-center justify-content-center">
    <div class="col-lg-3 col-md-12 mb-3">
      <%= link_to admin_member_path(@member) do %>
        <%= image_tag @member.get_profile_image(100,100), class: "image" %><br>
        <%= @member.nickname %>  
      <% end %> 
    </div>
  </div>

  <!-- 会員のレビュー一覧 -->
  <% if @reviews.present? %>
    <% @reviews.each do |review| %>
      <div class="row my-3 justify-content-center">
        <div class="col-lg-3 col-md-12 p-3 text-center display-box">
          <%= image_tag review.canned_food.get_image(200,100), class: "image" %><br>
          <%= review.canned_food.canned_name %>
        </div>
        <div class="col-lg-9 col-md-12 d-flex align-items-center justify-content-center display-box">
          <div class="row">
            <%= render "display", review: review %>
            <div class="col-12 text-center">
              <%= render "admin/comments/count", comment: review.comments %>
            </div>
            <div class="col-12 my-3 text-center">
              <%= link_to "レビュー詳細", admin_review_comments_path(review.id), class: "btn primary-button" %>
              <%= link_to "レビュー削除", admin_review_path(review.id), method: :delete, class: 'btn danger-button' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col my-5 text-center justify-content-center">
      <h3>レビューはありません。</h3>
    </div>
  <% end %>
  
  <div class="row">
    <div class="mx-auto my-5">
      <%= paginate @reviews %>
    </div>
  </div>
</div>