config/routes.rb
Rails.application.routes.draw do
  # 会員用
  devise_for :members, skip: [:passwords], controllers: 
  {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:
  {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "members_guest_sign_in"
  end
  
  scope module: :public do
    root to: "homes#top"
    
    get '/canned_foods/search' => 'canned_foods#search'
    get "/canned_foods/search_tag" => "canned_foods#search_tag"
    resources :canned_foods, only: [:index, :show]do
      resources :reviews, only: [:index]
    end
    
    get '/members/my_page' => 'members#index'
    get '/members/information/edit' => 'members#edit'
    patch '/members/information' => 'members#update'
    get '/members/unsubscribe' => 'members#unsubscribe'
    patch '/members/withdraw' => 'members#withdraw'
    resources :members, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    
    resources :reviews, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :index, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
    
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    
    # 新規会員登録失敗時の対処
    get "members" => redirect("/members/sign_up")
  end
  
  namespace :admin do
    resources :canned_foods, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index]
    end
    
    resources :members, only: [:index, :show, :edit, :update] 
    
    get '/members/:member_id/reviews' => 'reviews#show', as: "reviews_member"
    resources :reviews, only: [:destroy] do
      resources :comments, only: [:index, :destroy]
    end
    
    get "search" => "searches#search"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/canned_food.rb
class CannedFood < ApplicationRecord
  has_many :reviews, dependent: :destroy      # レビューとの関連付け
  has_many :favorites, dependent: :destroy    # お気に入りとの関連付け
  has_many :canned_tags, dependent: :destroy  # 缶詰タグとの関連付け
  has_many :tags, through: :canned_tags       # タグとの関連付け

  # 缶詰の画像用
  has_one_attached :image
  # 缶詰画像取得
  def get_image(width, height)
    unless image.attached?
      # デフォルトの画像を設定する
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
    end
    # 指定した幅と高さにリサイズした画像を返す
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索機能用
  def self.looks(word)
    @canned_food = CannedFood.where("canned_name LIKE?", "%#{word}%")
  end

  validates :canned_name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :is_canned_status, inclusion: { in: [true, false] }
end

app/controllers/admin/canned_foods_controller.rb
class Admin::CannedFoodsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @canned_foods = CannedFood.page(params[:page]).per(10)
  end

  def new
    @canned_food = CannedFood.new
  end

  def create
    @canned_food = CannedFood.new(canned_food_params)

    if params[:canned_food][:tag_ids] != "" && @canned_food.save
      # 中間テーブル缶詰タグの保存
      canned_tags = @canned_food.canned_tags.build(tag_id: params[:canned_food][:tag_ids])
      canned_tags.save!
      # 保存成功した場合の処理
      flash[:notice] = "缶詰の登録が完了しました。"
      redirect_to admin_canned_food_path(@canned_food.id)
    else
      # 保存失敗した場合の処理
      if params[:canned_food][:tag_ids] == ""
        flash[:alert] = "缶詰の登録が失敗しました。タグの選択を行って下さい。"
      else
        flash[:alert] = "缶詰の登録が失敗しました。"
      end

      render :new
    end
  end

  def show
    @canned_food = CannedFood.find(params[:id])
    @tags = @canned_food.tags
  end

  def edit
    @canned_food = CannedFood.find(params[:id])
    @tags = @canned_food.tags
  end

  def update
    @canned_food = CannedFood.find(params[:id])

    if params[:canned_food][:tag_ids] != "" && @canned_food.update(canned_food_params)
      # 中間テーブル缶詰タグの更新
      @canned_food.tag_ids = params[:canned_food][:tag_ids]
      # 更新成功した場合の処理
      flash[:notice] = "缶詰の更新が完了しました。"
      redirect_to admin_canned_food_path(@canned_food.id)
    else
      # 更新失敗した場合の処理
      if params[:canned_food][:tag_ids] == ""
        flash[:alert] = "缶詰の更新が失敗しました。タグの選択を行って下さい。"
      else
        flash[:alert] = "缶詰の更新が失敗しました。"
      end

      render :edit
    end
  end

  private
    def canned_food_params
      params.require(:canned_food).permit(:canned_name, :description, :image, :is_canned_status, tag_ids: [])
    end
end

app/helpers/admin/canned_foods_helper.rb
module Admin::CannedFoodsHelper
end

app/views/admin/canned_foods/_list.html.erb
<% if canned_foods.present? %>
  <table class="table text-center">
    <thead class="bg-success">
      <tr>
        <th class="font-weight-bold border border-dark">缶詰ID</th>
        <th class="font-weight-bold border border-dark">缶詰名</th>
        <th class="font-weight-bold border border-dark">画像</th>
        <th class="font-weight-bold border border-dark">タグ</th>
        <th class="font-weight-bold border border-dark">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% canned_foods.each do |canned_food| %>
        <tr>
          <td class="border border-dark"><%= canned_food.id %></td>
          <td class="border border-dark">
            <%= link_to admin_canned_food_path(canned_food.id) do %>
              <%= canned_food.canned_name %>
            <% end %>
          </td>
          <td class="border border-dark"><%= image_tag canned_food.get_image(100,50), class: "image" %></td>
          <td class="border border-dark">
            <% canned_food.tags.each do |tag| %>
              <%= tag.name %>
            <% end %>
          </td>
          <td class="border border-dark">
            <% if canned_food.is_canned_status == true %>
              <strong class="text-success"><%= "表示" %></strong>
            <% else %>
              <strong class="text-danger"><%= "非表示" %></strong>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="col text-center justify-content-center">
    <h3>缶詰が見つかりませんでした。</h3>
  </div>
<% end %>

app/views/admin/canned_foods/edit.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">缶詰編集</h2>
  </div>

  <%= form_with model: @canned_food, url: admin_canned_food_path(@canned_food), method: :patch do |f| %>
    <%= render "admin/shared/error_messages", resource: @canned_food %>
    <div class="row d-flex align-items-center justify-content-center">
      <table class="col-12 table-bordered table-information">
        <tbody>
          <tr class="field">
            <th class="col-lg-3 col-md-12 p-3 text-center table-info align-middle">
              缶詰名
            </th>
            <td class="col-lg-9 col-md-12 p-3 text-center align-middle">
              <%= f.text_field :canned_name, autofocus: true, placeholder: "缶詰名", class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-3 col-md-12 p-3 text-center table-info align-middle">
              缶詰説明
            </th>
            <td class="col-lg-9 col-md-12 p-3 text-center align-middle">
              <%= f.text_area :description, autofocus: true, placeholder: "ここに説明文を記述します", class: "form-control", cols: "80", rows: "10" %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-3 col-md-12 p-3 text-center table-info align-middle">
              缶詰画像
            </th>
            <td class="col-lg-9 col-md-12 p-3 text-center align-middle">
              <%= f.file_field :image, autofocus: true, accept: "image/*" %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-3 col-md-12 p-3 text-center table-info align-middle">
              缶詰タグ
            </th>
            <td class="col-lg-9 col-md-12 p-3 text-center align-middle">
              <%= f.collection_select :tag_ids, Tag.all, :id, :name, autofocus: true, multiple: true, include_blank: "--選択してください--", class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-3 col-md-12 p-3 text-center table-info align-middle">
              表示ステータス
            </th>
            <td class="col-lg-9 col-md-12 p-3 text-center align-middle">
              <%= f.radio_button :is_canned_status, :true,class:"form-check-input ml-2" %>
              <%= f.label :is_canned_status, "表示",class:"form-check-label ml-4" %>

              <%= f.radio_button :is_canned_status, :false,class:"form-check-input ml-2" %>
              <%= f.label :is_canned_status, "非表示",class:"form-check-label ml-4" %>
            </td>
          </tr>
        </tbody>
      </table>
      
      <div class="my-4 text-center">
        <%= f.submit "変更を保存", class: "btn edit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/canned_foods/index.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">缶詰一覧</h2>
    
    <div class="search_form offset-1 d-flex align-items-center">
      <%= render "admin/searches/form", word: "缶詰名", range: "缶詰"  %>
    </div>
  </div>
  
  <div class="row justify-content-end">
    <div class="col-lg-2 col-md-12 text-center">
      <h5>
        <%= link_to new_admin_canned_food_path do %>
          新規追加
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </h5>
    </div>
  </div>
    
  <div class="row">
    <%= render "admin/canned_foods/list", canned_foods: @canned_foods %>
  </div>
  
  <div class="row">
    <div class="mx-auto my-2">
      <%= paginate @canned_foods %>
    </div>
  </div>
</div>

app/views/admin/canned_foods/new.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">缶詰新規登録</h2>
  </div>
  
  <%= form_with model: @canned_food, url: admin_canned_foods_path, method: :post do |f| %>
    <%= render "admin/shared/error_messages", resource: @canned_food %>
    <div class="row mt-5 justify-content-center">
      <table class="table table-bordered text-center table-information">
        <tbody>
          <tr>
            <th class="p-3 text-center table-info align-middle">
              缶詰名
            </th>
            <td class="p-3 text-center align-middle">
              <%= f.text_field :canned_name, autofocus: true, placeholder: "缶詰名", class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th class="p-3 text-center table-info align-middle">
              缶詰説明
            </th>
            <td class="align-middle text-left text-break overflow-auto">
              <%= f.text_area :description, autofocus: true, placeholder: "ここに説明文を記述します", class: "form-control", rows: "7" %>
            </td>
          </tr>
          <tr>
            <th class="p-3 text-center table-info align-middle">
              缶詰画像
            </th>
            <td class="p-3 text-center align-middle">
              <%= f.file_field :image, autofocus: true, accept: "image/*" %>
            </td>
          </tr>
          <tr>
            <th class="p-3 text-center table-info align-middle">
              缶詰タグ
            </th>
            <td class="p-3 text-center align-middle">
              <%= f.collection_select :tag_ids, Tag.all, :id, :name, autofocus: true, multiple: true, include_blank: "--選択してください--", class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th class="p-3 text-center table-info align-middle">
              表示ステータス
            </th>
            <td class="p-3 text-center align-middle">
              <%= f.radio_button :is_canned_status, :true,class:"form-check-input ml-2" %>
              <%= f.label :is_canned_status, "表示",class:"form-check-label ml-4" %>

              <%= f.radio_button :is_canned_status, :false,class:"form-check-input ml-2" %>
              <%= f.label :is_canned_status, "非表示",class:"form-check-label ml-4" %>
            </td>
          </tr>
        </tbody>
      </table>
      
      <div class="my-4 text-center">
        <%= f.submit "新規登録", class: "btn fixing-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/canned_foods/show.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="col-md-auto col-sm-12 px-3 text-center">缶詰詳細</h2>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-lg-3 col-md-12 my-2 d-flex align-items-center justify-content-center">
      <%= image_tag @canned_food.get_image(200,100), class: "image" %>
    </div>
    
    <div class="col-lg-9 col-md-12">
      <table class="col-12 table-bordered table-information">
        <tbody>
          <tr>
            <th class="col-lg-4 col-md-12 p-3 text-center table-info align-middle">
              缶詰名
            </th>
            <td class="col-lg-8 col-md-12 p-3 text-center align-middle">
              <%= @canned_food.canned_name %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-4 col-md-12 p-3 text-center table-info align-middle">
              缶詰説明
            </th>
            <td class="col-lg-8 col-md-12 p-3 text-left text-break">
              <div class="overflow-auto description-box">
                <%=safe_join(@canned_food.description.split("\n"),tag(:br))%>
              </div>
            </td>
          </tr>
          <tr>
            <th class="col-lg-4 col-md-12 p-3 text-center table-info align-middle">
              缶詰タグ
            </th>
            <td class="col-lg-8 col-md-12 p-3 text-center align-middle">
              <% @tags.each do |tag| %>
                <%= tag.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th class="col-lg-4 col-md-12 p-3 text-center table-info align-middle">
              表示ステータス
            </th>
            <td class="col-lg-8 col-md-12 p-3 text-center align-middle">
              <% if @canned_food.is_canned_status == true %>
                <strong class="text-success"><%= "表示" %></strong>
              <% else %>
                <strong class="text-danger"><%= "非表示" %></strong>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="row my-5 justify-content-center">
    <div>
      <%= link_to "編集する", edit_admin_canned_food_path(@canned_food.id), class: "btn edit-button" %>
    </div>
    <div class="offset-1">
      <%= link_to "レビュー一覧", admin_canned_food_reviews_path(@canned_food.id), class: "btn primary-button" %>
    </div>
  </div>
</div>