config/routes.rb
Rails.application.routes.draw do
  # 会員用
  devise_for :members, skip: [:passwords], controllers: 
  {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:
  {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "members_guest_sign_in"
  end
  
  scope module: :public do
    root to: "homes#top"
    
    get '/canned_foods/search' => 'canned_foods#search'
    get "/canned_foods/search_tag" => "canned_foods#search_tag"
    resources :canned_foods, only: [:index, :show]do
      resources :reviews, only: [:index]
    end
    
    get '/members/my_page' => 'members#index'
    get '/members/information/edit' => 'members#edit'
    patch '/members/information' => 'members#update'
    get '/members/unsubscribe' => 'members#unsubscribe'
    patch '/members/withdraw' => 'members#withdraw'
    resources :members, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    
    resources :reviews, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :index, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
    
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    
    # 新規会員登録失敗時の対処
    get "members" => redirect("/members/sign_up")
  end
  
  namespace :admin do
    resources :canned_foods, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index]
    end
    
    resources :members, only: [:index, :show, :edit, :update] 
    
    get '/members/:member_id/reviews' => 'reviews#show', as: "reviews_member"
    resources :reviews, only: [:destroy] do
      resources :comments, only: [:index, :destroy]
    end
    
    get "search" => "searches#search"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canned_food.rb
class CannedFood < ApplicationRecord
  has_many :reviews, dependent: :destroy      # レビューとの関連付け
  has_many :favorites, dependent: :destroy    # お気に入りとの関連付け
  has_many :canned_tags, dependent: :destroy  # 缶詰タグとの関連付け
  has_many :tags, through: :canned_tags       # タグとの関連付け

  # 缶詰の画像用
  has_one_attached :image
  # 缶詰画像取得
  def get_image(width, height)
    unless image.attached?
      # デフォルトの画像を設定する
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
    end
    # 指定した幅と高さにリサイズした画像を返す
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索機能用
  def self.looks(word)
    @canned_food = CannedFood.where("canned_name LIKE?", "%#{word}%")
  end

  validates :canned_name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :is_canned_status, inclusion: { in: [true, false] }
end

app/models/canned_tag.rb
class CannedTag < ApplicationRecord
  belongs_to :canned_food # 缶詰に所属
  belongs_to :tag         # タグに所属
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member  # 会員に所属
  belongs_to :review  # レビューに所属

  # コメントの画像用
  has_one_attached :image
  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  validates :content, presence: true, length: { in: 1..100 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :member  # 会員に所属
  belongs_to :room    # ルームに所属
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member      # 会員に所属
  belongs_to :canned_food # 缶詰に所属

  validates :member_id, uniqueness: { scope: :canned_food_id }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy    # レビューとの関連付け
  has_many :comments, dependent: :destroy   # コメントとの関連付け

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy     # フォローしている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  # フォローされている関連付け
  has_many :followings, through: :active_relationships, source: :followed   # フォローしている会員を取得
  has_many :followers, through: :passive_relationships, source: :follower   # フォロワーを取得

  has_many :favorites, dependent: :destroy  # お気に入りとの関連付け
  has_many :favorite_canned_foods, through: :favorites, source: :canned_food  # お気に入りに関連するすべての缶詰

  has_many :entries, dependent: :destroy  # DM機能用の情報との関連付け
  has_many :messages, dependent: :destroy # DM機能用のメッセージとの関連付け


  # 会員の画像用
  has_one_attached :image
  # 会員のプロフィール画像取得
  def get_profile_image(width, height)
    unless image.attached?
      # デフォルトの画像を設定する
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
    end
    # 指定した幅と高さにリサイズした画像を返す
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 指定した会員をフォローする
  def follow(member)
    active_relationships.create(followed_id: member.id)
  end
  # 指定した会員のフォローを解除する
  def unfollow(member)
    active_relationships.find_by(followed_id: member.id).destroy
  end
  # 指定した会員をフォローしているかどうかを判定
  def following?(member)
    followings.include?(member)
  end

  # お気に入りに追加する
  def favorite(canned_food)
    favorite_canned_foods << canned_food
  end
  # お気に入りを外す
  def unfavorite(canned_food)
    favorite_canned_foods.destroy(canned_food)
  end
  # お気に入りにしているか判定する
  def favorite?(canned_food)
    favorite_canned_foods.include?(canned_food)
  end

  # 検索機能用
  def self.looks(search, word)
    if search == "partial"
      @member = Member.where("nickname LIKE?", "%#{word}%")
    end
  end

  # ゲスト会員用メールアドレス
  GUEST_MEMBER_EMAIL = "guest@example.com"
  # ゲスト会員用情報取得
  def self.guest
    find_or_create_by!(email: GUEST_MEMBER_EMAIL) do |member|
      member.password = SecureRandom.urlsafe_base64
      member.nickname = "ゲスト"
      member.phone_number = "XXXXXXXXXXX"
    end
  end
  # ゲスト会員の判定
  def guest_member?
    email == GUEST_MEMBER_EMAIL
  end

  validates :nickname, uniqueness: true, presence: true, length: { in: 1..12 }
  validates :phone_number, presence: true, numericality: { only_integer: true }, length: { in: 10..11 }
  devise :validatable, password_length: 6..32
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member  # 会員に所属
  belongs_to :room    # ルームに所属

  validates :content, presence: true, length: { in: 1..100 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Member"  # フォローする側の会員に所属
  belongs_to :followed, class_name: "Member"  # フォローされる側の会員に所属
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :member      # 会員に所属
  belongs_to :canned_food # 缶詰に所属

  has_many :comments, dependent: :destroy # コメントとの関連付け

  validates :expiry_date_rating, numericality: { in: 1..5 }
  validates :taste_rating, numericality: { in: 1..5 }
  validates :snack_rating, numericality: { in: 1..5 }
  validates :outdoor_rating, numericality: { in: 1..5 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy  # DM機能用の情報との関連付け
  has_many :messages, dependent: :destroy # DM機能用のメッセージとの関連付け
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :canned_tags, dependent: :destroy    # 缶詰タグとの関連付け
  has_many :canned_foods, through: :canned_tags # 缶詰との関連付け
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/canned_foods_helper.rb
module Admin::CannedFoodsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
 <div id="error_messages" class="alert alert-danger">
   <ul class="mb-0">
     <% resource.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto h-auto footer">
  <div class="container">
    <div class="row">
      <div class="col pt-3 text-center font-italic text-light">
        <p>Canned Food Galaxy</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark header">
    <div class="container">
      <a class="navbar-brand header-title" href="/">
        <span>缶詰の星へ</span>
      </a>
      
      <% if admin_signed_in? %>
        <p class="text-light mt-3 ml-auto">ようこそ、管理者さん！</p>
      <% elsif member_signed_in? %>
        <p class="text-light mt-3 ml-auto">ようこそ、<%= current_member.nickname %>さん！</p>
      <% end %>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_canned_foods_path ,class: 'nav-link text-light' do %>
              缶詰一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_members_path ,class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
        <% elsif member_signed_in? %>
          <li>
            <%= link_to canned_foods_path, class: 'nav-link text-light' do %>
              缶詰一覧
            <% end %>
          </li>
          <li>
            <%= link_to members_my_page_path, class: 'nav-link text-light' do %>
              マイページ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_member_session_path, method: :delete, class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to canned_foods_path, class: 'nav-link text-light' do %>
              缶詰一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_member_registration_path, class: 'nav-link text-light' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_member_session_path, class: 'nav-link text-light' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>缶詰の星</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/fb73c75996.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/jquery-raty-js@2.8.0/lib/jquery.raty.min.js"></script>
  </head>

  <body>
    <div class="footer-adjustments">
      <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      
      <main>
        <%= yield %>
      </main>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>